name: Hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: | 
          echo "wellcome to start"
          echo "wellcome out world"
          echo "jai shree ram"
